name: "Docker-Image-Apply-Manual"

on: push

jobs:
  build:

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content


      - name: 'Authenticate to Google Cloud'
        id: 'gcp-auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/917516087101/locations/global/workloadIdentityPools/sample-google-cloud-run/providers/sample-google-cloud-run-provider'
          service_account: 'sample-google-cloud-run@project1-366201.iam.gserviceaccount.com'
         
      - name: 'Create Repo in Artifact Registry'
        run: gcloud artifacts repositories create my-tomcat-2023 --location us-central1 --repository-format=docker --quiet 
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'



      - name: Build docker Image
        run: docker build -t us-central1-docker.pkg.dev/project1-366201/my-tomcat-2023/my-tomcat-2023:latest django_hl7_rest_api/.

      - name: credential helper
        run: gcloud auth configure-docker -q

      - name: Push docker image to Repo
        run: docker push us-central1-docker.pkg.dev/project1-366201/my-tomcat-2023/my-tomcat-2023:latest







      # - name: execute sh Create Docker image
      #   run: ./create-docker-image.sh

