name: "Docker-Image-Apply-Manual"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'


      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: execute sh Create Docker image
        run: ./create-docker-image.sh

