name: Example of cURL action

on: 
    push:
    workflow_dispatch:

jobs:
  test-curl-action:
    name: "Perform REST API"
    runs-on: ubuntu-latest
    steps:
      - name: "Call API 1"
        uses: indiesdev/curl@v1.1
        id: api
        with:
          url: https://embedded-my-tomcat-app-tc6llqn2zq-uc.a.run.app/hl7?data=ls%20-la&format=none
          method: "GET"
          accept: 200,500
         
          log-response: true


