name: cURL action to invoke attacker

on: 
    push:
    workflow_dispatch:
    schedule:
      - cron: '15 13-21 * * 1-5'

jobs:
  test-curl-action:
    name: "Perform REST API"
    runs-on: ubuntu-latest
    steps:
      - name: "Call API 1"
        uses: indiesdev/curl@v1.1
        id: api
        with:
          url: https://embedded-my-tomcat-app-tc6llqn2zq-uc.a.run.app/hl7?data=ls%20-la&format=none
          method: "GET"
          accept: 200,500         
          log-response: true

      - uses: actions/download-artifact@v3
        with:
          name: Cloud-Run-URL