name: "Workflow Create"

#on: workflow_dispatch
on:
  push:
    branches:
      - main

jobs:
  build:

    env:
      application_name: "embedded-my-tomcat-app"
      PCC_API: ${{ secrets.PCC_API }}
      PCC_KEY: ${{ secrets.PCC_KEY }}
      PCC_SEC: ${{ secrets.PCC_SEC }}
      service_account : "sample-google-cloud-run@project1-366201.iam.gserviceaccount.com"
      workload_identity_provider: "projects/917516087101/locations/global/workloadIdentityPools/sample-google-cloud-run/providers/sample-google-cloud-run-provider"

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r policy/requirements.txt

      - name: execute py Collections Script 
        run: python policy/create-collection.py

      - name: execute py Policy Script 
        run: python policy/create-policy.py

      - name: 'Authenticate to Google Cloud'
        id: 'gcp-auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{env.workload_identity_provider}}'
          service_account: '${{env.service_account}}'


      - name: 'Create Repo in Artifact Registry'
        run: gcloud artifacts repositories create my-tomcat-2023 --location us-central1 --repository-format=docker --quiet 
  
      - name: Create Compute Login Token 
        run: python policy/create-token.py      

      - name: execute sh Create Docker image
        run: ./create-docker-image.sh

      - name: Build docker Image
        run: docker build -t us-central1-docker.pkg.dev/project1-366201/my-tomcat-2023/my-tomcat-2023:latest django_hl7_rest_api/.

      - name: credential helper
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Push docker image to Repo
        run: docker push us-central1-docker.pkg.dev/project1-366201/my-tomcat-2023/my-tomcat-2023:latest


      - name: Deploy image to Google Cloud Run
        run: gcloud run deploy my-tomcat-2023 --region us-central1 --image=us-central1-docker.pkg.dev/project1-366201/my-tomcat-2023/my-tomcat-2023:latest  --concurrency 1 --allow-unauthenticated

      - name: Allow unauthenticated
        run: gcloud run services add-iam-policy-binding my-tomcat-2023 --member="allUsers" --role="roles/run.invoker" --region us-central1 
  
