name: "Workflow Delete"

#on: push
on: workflow_dispatch



jobs:
  build:

    env:
      application_name: "embedded-my-tomcat-app"
      PCC_API: ${{ secrets.PCC_API }}
      PCC_KEY: ${{ secrets.PCC_KEY }}
      PCC_SEC: ${{ secrets.PCC_SEC }}
      service_account : "sample-google-cloud-run@project1-366201.iam.gserviceaccount.com"

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r policy/requirements.txt

      - name: execute py Policy Script 
        run: python policy/delete-policy.py

      - name: execute py Collections Script 
        run: python policy/delete-collection.py

      - name: 'Authenticate to Google Cloud'
        id: 'gcp-auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{env.workload_identity_provider}}'
          service_account: '${{env.service_account}}'

      - name: Delete Service
        run: gcloud run services delete my-tomcat-2023 --region us-central1 --quiet

      - name: 'Create Repo in Artifact Registry'
        run: gcloud artifacts repositories delete my-tomcat-2023 --location us-central1 --quiet 
  


  
